version: "3"
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=caluma
      - POSTGRES_PASSWORD=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data

  caluma:
    image: projectcaluma/caluma:latest@sha256:333802b7fff16ea2aa52023e58a4e49d2989c58b49d6f92a9b52b752e41e8e9d
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ENV=docker
      #- MINIO_STORAGE_ENDPOINT=localhost:9000

  minio:
      image: minio/minio:latest@sha256:eec714a5c50799ae70004fcd3f5d54bd63a759ecaf0033eeb4e2906c18270133
      volumes:
        - minio_data:/data
      ports:
        - "9000:9000"
      environment:
        - MINIO_ACCESS_KEY=minio
        - MINIO_SECRET_KEY=minio123
        - MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET=True
      command: server data

volumes:
  dbdata:
  minio_data: